"""Local, infra-free smoke test of the autonomous-supply-chain DETECT -> DECIDE logic.

WHAT THIS PROVES (offline, no Databricks / no AWS / no Amazon Quick):
  1. The Genie "surge" trusted SQL (genie/genie_surge_trusted_query.sql) selects exactly the
     intended surging SKUs when run against representative forecast/actual data.
  2. The supplier economics generated by the repo's own loader
     (supplier-feed/load_supplier_availability.py) reconcile to the blog's headline decision:
     a covered surge -> the cheapest supplier that covers within lead time places a routine order;
     and the deliberately under-supplied SKU (retailer product 122 / Boston) -> no single supplier
     covers -> exception (ticket) path.

WHAT THIS DOES NOT COVER (needs live infra, tracked separately):
  - Chronos-2 forecast accuracy (Serverless GPU notebook 02)
  - Amazon Quick MCP/OAuth, S3 Tables Direct Query, Quick Flows orchestration (console-only)
  - The deployed Order API round-trip (needs AWS creds + CloudFormation)

Run:  uv run --python 3.11 --with duckdb --with pandas --with pyarrow smoketest/local_logic_smoketest.py
"""
from __future__ import annotations
import sys
from pathlib import Path

import duckdb
import pandas as pd

REPO = Path(__file__).resolve().parent.parent
FAILURES: list[str] = []


def check(name: str, got, want) -> None:
    ok = got == want
    print(f"  [{'PASS' if ok else 'FAIL'}] {name}: got={got!r} want={want!r}")
    if not ok:
        FAILURES.append(name)


# --------------------------------------------------------------------------- load repo loader consts
# The loader imports pyiceberg at module top (heavy, needs AWS). To keep this test infra-free we parse
# the constants we depend on straight from the source with the `ast` module — so we still use the
# loader's REAL values (single source of truth) without importing/executing it.
#
# NOTE: PROFILES / BASE_COST are module-level, but DAILY_BASE and UNDER_SUPPLIED live INSIDE
# build_supplier_rows() (they are function-local). So we walk the whole tree (ast.walk), not just
# tree.body, and take the first literal assignment for each name.
class LoaderConsts:
    CITY_GEO: dict
    PROFILES: list
    BASE_COST: float
    DAILY_BASE: dict
    UNDER_SUPPLIED: dict


def load_loader_module() -> LoaderConsts:
    import ast
    path = REPO / "supplier-feed" / "load_supplier_availability.py"
    tree = ast.parse(path.read_text())
    wanted = {"CITY_GEO", "PROFILES", "BASE_COST", "DAILY_BASE", "UNDER_SUPPLIED"}
    found: dict = {}
    for node in ast.walk(tree):            # walk() so we also reach function-local assigns
        if isinstance(node, ast.Assign):
            for t in node.targets:
                if isinstance(t, ast.Name) and t.id in wanted and t.id not in found:
                    try:
                        found[t.id] = ast.literal_eval(node.value)
                    except (ValueError, SyntaxError):
                        pass               # non-literal RHS — ignore, keep looking
    missing = wanted - set(found)
    if missing:
        raise SystemExit(f"could not parse loader constants: {missing}")
    c = LoaderConsts()
    c.CITY_GEO = found["CITY_GEO"]
    c.PROFILES = found["PROFILES"]
    c.BASE_COST = found["BASE_COST"]
    c.DAILY_BASE = found["DAILY_BASE"]
    c.UNDER_SUPPLIED = found["UNDER_SUPPLIED"]
    return c


# --------------------------------------------------------------------------- surge SQL (DuckDB port)
# This is genie/genie_surge_trusted_query.sql with only DIALECT swaps for DuckDB:
#   split_part(x,'_',2) -> same in DuckDB; try_divide -> divide via NULLIF; table names -> temp views.
SURGE_SQL = """
WITH forecast_stats AS (
  SELECT unique_id,
         AVG(forecast_value) AS avg_forecast,
         SUM(forecast_value) AS forecast_7d_total
  FROM scoring_output_mv
  WHERE forecast_date >= DATE '2024-06-26' AND forecast_date <= DATE '2024-07-02'
  GROUP BY unique_id),
actual_stats AS (
  SELECT unique_id,
         AVG(y)       AS avg_actual,
         MAX(city_id) AS city_id
  FROM demand_train
  WHERE ds >= DATE '2024-06-12' AND ds <= DATE '2024-06-25'
  GROUP BY unique_id)
SELECT f.unique_id,
       CAST(split_part(f.unique_id, '_', 2) AS INT) AS retailer_product_id,
       a.city_id,
       l.region,
       l.city_name,
       f.forecast_7d_total,
       (f.avg_forecast / NULLIF(a.avg_actual, 0))    AS surge_ratio
FROM forecast_stats f
JOIN actual_stats   a ON f.unique_id = a.unique_id
JOIN location_dim   l ON a.city_id = l.city_id
WHERE f.avg_forecast >= 1.5 * a.avg_actual
  AND a.avg_actual   >= 1
ORDER BY surge_ratio DESC
"""

# The six intended surging SKUs (from the notebook 03 validation cell + runbook Tier 2.1).
HERO_SKUS = {"18_122", "450_300", "3_191", "299_300", "561_261", "375_4"}
# unique_id = "<store>_<product>"; city_id is carried on demand_train (NOT the store prefix).
# Build representative daily rows: 14 prior-actual days (Jun 12-25) + 7 forecast days (Jun 26-Jul 2).
SKU_CITY = {  # map each hero SKU to a city_id whose region we assert on
    "18_122": 0,    # Boston / Northeast (hero "Skim Milk"; the DELIBERATELY under-supplied SKU)
    "450_300": 6,   # Chicago / Midwest
    "3_191": 1,     # New York / Northeast
    "299_300": 9,   # Dallas / Southwest
    "561_261": 16,  # Denver / West
    "375_4": 12,    # Los Angeles / West
}
# per-SKU (avg_actual/day, avg_forecast/day) chosen to yield surge ratios ~1.5-1.7x
SKU_LEVELS = {
    "18_122":  (4.26, 7.18),   # ~1.69x  hero -> ~50u/7d, under-supplied -> ticket
    "450_300": (10.0, 15.5),   # 1.55x
    "3_191":   (8.0, 12.8),    # 1.60x
    "299_300": (9.0, 14.0),    # 1.56x
    "561_261": (30.0, 51.0),   # 1.70x
    "375_4":   (6.0, 9.6),     # 1.60x
}
# a few NON-surging SKUs to prove the filter excludes them
NOISE = {"7_55": (10.0, 10.5, 3), "8_9": (5.0, 6.0, 4)}  # ratio <1.5 or flat


def build_mock_frames(loader):
    fdates = pd.date_range("2024-06-26", periods=7, freq="D").date
    adates = pd.date_range("2024-06-12", periods=14, freq="D").date

    scoring, demand = [], []
    for sku, (a_day, f_day) in SKU_LEVELS.items():
        city = SKU_CITY[sku]
        for d in fdates:
            scoring.append({"unique_id": sku, "forecast_date": d, "forecast_value": f_day})
        for d in adates:
            demand.append({"unique_id": sku, "ds": d, "y": a_day, "city_id": city,
                           "product_id": int(sku.split("_")[1])})
    for sku, (a_day, f_day, city) in NOISE.items():
        for d in fdates:
            scoring.append({"unique_id": sku, "forecast_date": d, "forecast_value": f_day})
        for d in adates:
            demand.append({"unique_id": sku, "ds": d, "y": a_day, "city_id": city,
                           "product_id": int(sku.split("_")[1])})

    # location_dim from the loader's OWN CITY_GEO map (single source of truth for geography)
    loc = [{"city_id": cid, "city_name": n, "region": r, "state": s}
           for cid, (n, r, s) in loader.CITY_GEO.items()]
    return pd.DataFrame(scoring), pd.DataFrame(demand), pd.DataFrame(loc)


def cheapest_covering_supplier(loader, retailer_pid: int, city_id: int, demand_units: float):
    """Reproduce the DECIDE step using the loader's REAL economics and availability generation.

    This mirrors build_supplier_rows() exactly: per-supplier daily base comes from the loader's
    DAILY_BASE, OVERRIDDEN by UNDER_SUPPLIED for the deliberately-starved (product, city) pairs; the
    7-day capacity applies the same deterministic ±8% wobble; unit cost is BASE_COST * cost_factor.
    Returns (chosen_tag_or_None, options) where each option lists 7-day qty/cost/lead per supplier.
    """
    fdays = 7
    opts = []
    for tag, cap_mult, lead, cost_factor in loader.PROFILES:
        # KEY FIX: honor UNDER_SUPPLIED so the starved SKU (122, 0) uses its real, lower base — the
        # same lookup the loader does (UNDER_SUPPLIED.get((pid, city), DAILY_BASE)[tag]).
        base_daily = loader.UNDER_SUPPLIED.get((retailer_pid, city_id), loader.DAILY_BASE)[tag]
        qty7 = 0
        for di in range(fdays):
            wobble = 1.0 + 0.08 * ((di % 3) - 1)   # -8%, 0, +8% cycling; matches the loader
            qty7 += int(round(base_daily * wobble))
        unit_cost = round(loader.BASE_COST * cost_factor, 2)
        opts.append({"tag": tag, "qty_7d": qty7, "lead": lead, "unit_cost": unit_cost,
                     "covers": qty7 >= demand_units})
    covering = [o for o in opts if o["covers"]]
    chosen = min(covering, key=lambda o: o["unit_cost"])["tag"] if covering else None
    return chosen, opts


def main() -> int:
    loader = load_loader_module()
    scoring, demand, loc = build_mock_frames(loader)

    con = duckdb.connect()
    con.register("scoring_output_mv", scoring)
    con.register("demand_train", demand)
    con.register("location_dim", loc)

    print("\n== TEST 1: surge DETECT SQL (the real trusted query, DuckDB dialect) ==")
    res = con.execute(SURGE_SQL).df()
    surging = set(res["unique_id"])
    check("surging SKU count", len(surging), 6)
    check("surging SKUs == intended hero set", surging == HERO_SKUS, True)
    # hero SKU geography resolves via location_dim (not store prefix)
    hero = res[res.unique_id == "18_122"].iloc[0]
    check("hero 18_122 region", hero["region"], "Northeast")
    check("hero 18_122 retailer_product_id (after underscore)", int(hero["retailer_product_id"]), 122)
    print("\n  surging rows:")
    print(res.to_string(index=False))

    print("\n== TEST 2: DECIDE — cheapest supplier that covers (loader economics) ==")
    # Routine ORDER: retailer product 300 (Chicago/city 6) is normally supplied. A ~50u surge is
    # covered by S1 (83) and S2 (55) but NOT S3 (28); S2 is the cheapest that covers -> routine order.
    chosen_order, opts_order = cheapest_covering_supplier(loader, 300, 6, 50)
    print("  supplier options for product 300 @ 50-unit surge (normal supply):")
    for o in opts_order:
        print(f"    {o['tag']}: qty_7d={o['qty_7d']} lead={o['lead']}d ${o['unit_cost']} covers={o['covers']}")
    check("normal 50u surge (prod 300) -> cheapest covering supplier", chosen_order, "S2")
    check("S3 cannot cover 50u alone", [o for o in opts_order if o["tag"] == "S3"][0]["covers"], False)

    # EXCEPTION -> ticket: retailer product 122 (Boston/city 0) is the deliberately under-supplied SKU
    # (loader UNDER_SUPPLIED). Its 7-day capacity is S1~35 / S2~28 / S3~21 — none covers the ~50u
    # surge — so NO single supplier covers -> exception (ticket) path. This is the blog's headline result.
    chosen_exc, opts_exc = cheapest_covering_supplier(loader, 122, 0, 50)
    print("  supplier options for product 122 @ 50-unit surge (UNDER-supplied):")
    for o in opts_exc:
        print(f"    {o['tag']}: qty_7d={o['qty_7d']} lead={o['lead']}d ${o['unit_cost']} covers={o['covers']}")
    check("under-supplied (122,0) uses UNDER_SUPPLIED base, not DAILY_BASE",
          max(o["qty_7d"] for o in opts_exc) < 50, True)
    check("no single supplier covers product 122 -> ticket", chosen_exc, None)

    con.close()
    print("\n" + ("=" * 60))
    if FAILURES:
        print(f"RESULT: {len(FAILURES)} FAILED -> {FAILURES}")
        return 1
    print("RESULT: ALL PASSED — detect+decide logic verified offline.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
